# Arguments for a VQ-VAE model trained on the val dataset.
dataset_path: "data/vae_data/"
model_path: "models/flexvae/model.pt"
results_path: "results/flexvae/"
model_params:
  codebook_size: 8192
  codebook_embed_dim: 8
  codebook_l2_norm: True
  codebook_show_usage: True
  commitment_loss_weight: 0.25 
  diversity_loss_weight: 0.05
  confidence_loss_weight: 0.001
  entropy_temperature: 0.01
  encoder_ch_mult: [1, 2, 2, 4]
  decoder_ch_mult: [1, 2, 2, 4]
  channels: 64
  z_channels: 128
  dropout_p: 0.0
patch_nums: [1, 2, 4, 8, 16]
imsize: 128
recon_loss_weight: 1.0        
batch_size: 16
num_epochs: 100
lr: 3e-4
weight_decay: 1e-5